# This script creates a pie chart showing the proportions of the Recombinant sub-lineages detected in a run.
# As input, it requires:
# 1 - the SummaryReport Excel file generated by wgs_script_report_format.R
# 2 - the text file generated by wgs_script_prebin.sh, which contains the raw Recombinant sub-lineage percentges

library(readxl)
library(dplyr)
library(ggplot2)
library(ggrepel)
library(RColorBrewer)

# import data
wgs <- read_xlsx("WGSseq052_20230717_SummaryReport.xlsx", sheet="Sheet1")[,1:31]
xxx <- read.table("pre_binned_lineages_combinedreporttoDoH.txt")

# add column names
colnames(xxx) <- c("lineage","percent","bin","sample")

# remove failed samples
xxx <- xxx[substr(xxx$sample,1,4) %in% (substr(wgs$RNA_ID[wgs$`Sequencing QC` == "Pass"],5,12)),]

# subset Recombinants
yyy <- xxx[xxx$bin == "Recombinant",]

# aggregate by recombinant type
zzz <- aggregate(percent ~ lineage , data = yyy, FUN = sum)

# -------------------- # --------------------

# pie chart

# calculate percentages
zzz$percent <- (zzz$percent/sum(zzz$percent))*100

# create percentage text
zzz$percent2 <- scales::percent(zzz$percent, accuracy = 0.1, scale = 1)

# create values for sorting
nnn <- nrow(zzz)
zzz$order <- 1:nnn

# sort
zzz <- arrange(zzz, desc(order))

# calculate label positions
zzz$posis <- ((cumsum(zzz$percent)) - (zzz$percent/2))

# create label text
zzz$label_text <- paste(zzz$lineage, sep = " ", zzz$percent2)

# create colour pallette
mycolors <- colorRampPalette(brewer.pal(9, "Set1"))(nnn)
randomcolors <- sample(mycolors)

ggplot(zzz, aes(x = "", y = percent, fill = lineage)) +
  geom_bar(width = 7, stat = "identity", color="white", show.legend = FALSE) +
  coord_polar(theta = "y", start = 0, direction = 1) +
  geom_label_repel(aes(label = label_text, y = posis),
                   seed = 1,
                   nudge_x = 5,
                   nudge_y = 2,
                   size = 3.5,
                   show.legend = FALSE,
                   max.overlaps = Inf,
                   segment.size = 0.2,
                   box.padding = 0.5) +
  scale_fill_manual(values = randomcolors) +
  theme_void()

ggsave("Recombinant_pie.pdf", width = 297, height = 210, units = "mm")

# -------------------- # --------------------
